# Generated by Django 3.2.25 on 2026-01-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='budget',
            field=models.CharField(choices=[('under_250', 'Under £250'), ('250_500', '£250 – £500'), ('500_1000', '£500 – £1,000'), ('1000_2000', '£1,000 – £2,000'), ('over_2000', 'Over £2,000'), ('unsure', "I'm not sure yet")], default='unsure', max_length=20),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('either', 'Email or phone')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='reference_url',
            field=models.URLField(blank=True, help_text='Optional link to inspiration, social media or similar work.'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='timeframe',
            field=models.CharField(choices=[('asap', 'ASAP'), ('two_weeks', 'Within 2 weeks'), ('month', 'Within a month'), ('flexible', 'Flexible / not urgent')], default='flexible', max_length=20),
        ),
    ]
