# Generated by Django 3.2.25 on 2026-01-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('design', 'Design'), ('photo', 'Photography'), ('video', 'Video & Editing'), ('three_d', '3D & Motion')], max_length=20)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField(blank=True)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
