# Generated by Django 3.2.25 on 2026-01-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional link to the live site, video or external project page.'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='portfolio_type',
            field=models.CharField(choices=[('web', 'Web & Digital Projects'), ('media', 'Photography & Media')], default='media', max_length=10),
        ),
    ]
