# Generated by Django 3.2.25 on 2026-01-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20260103_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='collection',
            field=models.CharField(choices=[('three_d', '3D Logo Animation'), ('photo', 'Photography & Video'), ('branding', 'Branding & Visual Design')], default='photo', max_length=20),
        ),
    ]
