# Generated by Django 3.2.25 on 2026-01-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioitem_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='collection',
            field=models.CharField(choices=[('web', 'Web & Digital Projects'), ('photo', 'Photography & Video'), ('three_d', '3D & Motion'), ('branding', 'Branding & Visual Design')], default='photo', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='portfolio_type',
            field=models.CharField(choices=[('web', 'Web & Digital Projects'), ('media', 'Photography & Media'), ('drone', 'Drone & Aerial')], default='media', max_length=10),
        ),
    ]
