# Generated by Django 3.2.25 on 2026-01-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20260104_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='collection',
            field=models.CharField(choices=[('web', 'Web & Digital Projects'), ('photo', 'Photography & Video'), ('drone', 'Drone & Aerial'), ('three_d', '3D & Motion'), ('branding', 'Branding & Visual Design')], default='photo', max_length=20),
        ),
    ]
