# Generated by Django 3.2.25 on 2026-01-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolioitem_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='section',
            field=models.CharField(blank=True, help_text='Optional sub-section, e.g. Portraits & Lifestyle, Scenic & Coastal Imagery, Events', max_length=120),
        ),
    ]
