# Generated by Django 4.2.27 on 2026-01-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Show this item in the homepage photography highlights strip.'),
        ),
    ]
