# Generated by Django 4.2.27 on 2026-01-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_portfolioitem_show_on_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='show_on_homepage',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='show_in_drone_highlights',
            field=models.BooleanField(default=False, help_text='Show this item in the homepage ‘Drone & Aerial Footage’ area.'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='show_in_photography_highlights',
            field=models.BooleanField(default=False, help_text='Show this item in the homepage ‘Photography highlights’ strip.'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='show_in_recent_work',
            field=models.BooleanField(default=False, help_text='Show this item in the homepage ‘Recent work’ section.'),
        ),
    ]
